project_id = "netzgkrlmoqsnvckzbkh"

[functions.fetch-cargas]
verify_jwt = false

[functions.whatsapp-connect]
verify_jwt = false

[functions.whatsapp-send]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.login-with-ip-check]
verify_jwt = false

[functions.analyze-feedback-keywords]
verify_jwt = true

[functions.process-audio]
verify_jwt = false

[functions.process-image]
verify_jwt = false

[functions.process-media]
verify_jwt = false