project_id = "netzgkrlmoqsnvckzbkh"

[functions.fetch-cargas]
verify_jwt = true

[functions.whatsapp-connect]
verify_jwt = true

[functions.whatsapp-send]
verify_jwt = true

[functions.whatsapp-send-template]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.login-with-ip-check]
verify_jwt = false

[functions.analyze-feedback-keywords]
verify_jwt = true

[functions.process-audio]
verify_jwt = false

[functions.process-image]
verify_jwt = false

[functions.process-media]
verify_jwt = false

[functions.whatsapp-media-proxy]
verify_jwt = false

[functions.campaign-send]
verify_jwt = true

[functions.send-satisfaction-survey]
verify_jwt = true

[functions.expire-pending-surveys]
verify_jwt = false

[functions.sync-order-details]
verify_jwt = true

[functions.whatsapp-send-media]
verify_jwt = true

[functions.fetch-profile-picture]
verify_jwt = true

[functions.clear-data]
verify_jwt = true

[functions.monitor-delivered-orders]
verify_jwt = true

[functions.generate-satisfaction-insights]
verify_jwt = true

[functions.finalize-pending-surveys]
verify_jwt = true

[functions.abort-survey-send]
verify_jwt = true

[functions.auto-template-sender]
verify_jwt = true
